version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}

  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app  # Copy source code to container
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  mongodb_data:
